export const LOGIN_SUCCESS = ' LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGOUT = 'LOGOUT';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const RESET_OK = 'RESET_OK';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const GET_PROFILE = 'GET_PROFILE';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const SET_ALERT = 'SET_ALERT';
export const POST_ERROR = 'POST_ERROR';
export const GET_POSTS = 'GET_POSTS';
export const GET_POST = 'GET_POST';
export const UPDATE_LIKES = 'UPDATE_LIKES';
export const DELETE_POST = 'DELETE_POST';
export const ADD_POST = 'ADD_POST';
export const ADD_COMMENT = 'ADD_COMMENT';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';
export const RATE = 'RATE';
export const ADD_FRIEND='ADD_FRIEND'
export const ADD_FRIEND_FAILED ='ADD_FRIEND_FAILED'
export const SEARCH_SUCCESS ='SEARCH_SUCCESS'
export const SEARCH_FAILED ='SEARCH_FAILED'
export const GET_COMMENT ='GET_COMMENT'
export const UPDATE_COMMENT ='UPDATE_COMMENT'
export const ERROR_UPDATE='ERROR_UPDATE'
export const GET_INV = 'GET_INV'
export const INV_ERROR = 'INV_ERROR'
export const ACC_INV = 'ACC_INV'
export const ACC_ERROR = 'ACC_ERROR'
export const EDIT_PIC ='EDIT_PIC'
export const ADD_EVENT='ADD_EVENT'
export const EVENT_ERROR='EVENT_ERROR'
export const GET_EVENTS='GET_EVENTS'
export const GET_EVENT='GET_EVENT'
export const DELETE_EVENT='DELETE_EVENT'
export const GET_CATEGORIES ='GET_CATEGORIES'
export const FILTER_EVENT ='FILTER_EVENT' 
export const GET_FRIENDS ='GET_FRIENDS'
export const INVITE_FRIENDS ='INVITE_FRIENDS'
export const UPDATE_EVENT ='UPDATE_EVENT'
